### ISSUE TITLE
Facebook event photo size

### ISSUE THREAD

**Issue by jeancharlesamey** [chuckreynolds/social-profile-image-sizes#4]
Hey Chuck,
Looking for the Event Photo Size : 16:9 ratio : 1920x1080
I found the answer here : https://www.facebook.com/help/community/question/?id=10153088168126867

Have a nice day

**Comment by chuckreynolds** [comment]
(_omg your profile photo lol..._)
In typical Facebook fashion you'll most likely never get a straight answer from them. Here it says `1200x628` [(source)](https://www.facebook.com/help/1910675759253872) and videos would always be in 1080p res. 

When creating an event FB gives me these warnings:
- small image: `Please choose an image that is at least 400 X 150 pixels.` (_which is 8:3 ratio_)
- vertical video exported from insta-story: `The video you selected is too tall. Aspect ratios for videos need to be between 2:1 and 1:1.`

When uploading a `1920x1080` video it seems to allow me to drag it up and down a little to position so they're not honoring 16:9 perfectly. Again, they're never specific, and they change things constantly, but maybe stick to that 2:1 ratio as per their warning? Or just go 16x9 and deal with a little crop. When the event is created the displayed image is `500x262` on my laptop.  If I add this to the list I think I'm just going to say 16x9 with slight vertical crop.

Test event is here for reference: https://www.facebook.com/events/426169574482060/
