### ISSUE TITLE
Instagram story size

### ISSUE THREAD

**Issue by jeancharlesamey** [chuckreynolds/social-profile-image-sizes#5]
Found some answers here, but nothing official 
https://medium.com/@mikemurphyco/134-quick-tip-pixel-dimensions-for-instagram-stories-62027f5c3319

**Comment by chuckreynolds** [comment]
An exported video from my story is `720 x 1280` and I'm on an iphone 8+. But, like that article says, I'd assume full HD video resolution and turn it 90º. I'll add that in. Thx for the issue!
