### ISSUE TITLE
Facebook sizes out of date?

### ISSUE THREAD

**Issue by cpence** [chuckreynolds/social-profile-image-sizes#7]
Not sure about the current numbers (I did a quick search but couldn't find any info), but Facebook complains about a 300x300 image that it "is small and will appear less clear," and the 851x315 cover image I produced had to be dragged around to be repositioned. (Is there a difference between "page" profiles/covers and "personal" profiles/covers, perhaps? This was for a page, not a personal account.)

**Comment by cpence** [comment]
Ah, finally found a page that looks up to date with the image sizes. (There's some resizing shenanigans going on behind the scenes, unsurprisingly.) See: https://dustn.tv/facebook-image-sizes/

**Comment by chuckreynolds** [comment]
This is why this is a repo - to keep it up to date and make changes :)

So the profile photo, [linked at bottom in sources](https://www.facebook.com/help/388305657884730/), says now 320x320 so I'll update that. _(Anything that's a profile photo should probably be uploaded at a larger square image anyway - let the site resize it as they will. I typically have a 600x600 or 800x800 square ready for almost every site)_.

As far as profile covers - if you [look at their docs they still say that 851x315 size](https://www.facebook.com/help/266520536764594/). 

If you look at Page covers.... [they say 820x312 is what they'll resize it to but right below that they still mention the same 851x315 size](https://www.facebook.com/help/125379114252045?helpref=uf_permalink); which is what I've kept this guide at based on the source documentation.

Pushing an update for the profile images in a bit. 
Thx for the issue!
