### ISSUE TITLE
Github profile picture size is 400px x 400px

### ISSUE THREAD

**Issue by INZAME** [chuckreynolds/social-profile-image-sizes#8]

**Comment by chuckreynolds** [comment]
i have 500x500 listed which would resize anyway so... is there really a need to change to to 400x400?

**Comment by INZAME** [comment]
resize from 500x500 can cause small artifacts, it's not critical

**Comment by chuckreynolds** [comment]
changed to 460 based on https://github.com/chuckreynolds/social-profile-image-sizes/pull/9
